# Generated by Django 3.0.8 on 2020-11-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_teacher',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_student',
        ),
    ]
